CREATE EXTENSION IF NOT EXISTS citext;
--;;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
--;;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
--;;
CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  username CITEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  date_created TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);
